spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.lrm: debug
  file:
    path:
    name: blog-dev.log

server:
  port: 7777