spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog
    password: s2M2NNey7bkJnkXG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: warn
    com.lrm: info
  file:
    path: log
    name: blog-pro.log
server:
  port: 80
